# Site
title:              Michalis Spyrou
bio:                'Software Engineer based in the United Kingdom'
description:        "My interests focus on performance improvement and power efficiency on embedded and heterogeneous systems and also parallel programming for multicore and manycore systems. Also interested in computer security, mainly as a hobby."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
#url:                mispyrou.com

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   mispyrou

# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            #username
  analytics:        UA-112445278-1
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              mispyrou@gmail.com
twitter:            mpekatsoula
github-url:         mpekatsoula
linkedin:           michalis-spyrou-86635b57
#xing:              username
#instagram:          username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
